name: Deploy Flask API

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed for OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy via AWS SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Falcons Stats Flask API" \
            --parameters '{"commands":[
              "sudo yum install -y git python3 python3-pip",
              "pip3 install --upgrade pip",
              "[[ -x $(command -v poetry) ]] || (curl -sSL https://install.python-poetry.org | python3 - && echo \"export PATH=$HOME/.local/bin:$PATH\" >> ~/.bashrc && source ~/.bashrc)",
              "cd /home/ssm-user",
              "[[ -d falcons-stats ]] || git clone https://github.com/banana-bread/falcons-stats.git falcons-stats",
              "cd falcons-stats",
              "git pull origin main",
              "poetry install --no-dev --no-interaction",
              "sudo systemctl restart falcons-stats.service"
            ]}' \
            --output text
