name: "Terraform Apply"
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.AWS_S3_BUCKET_NAME }}" \
            -backend-config="key=${{ secrets.AWS_S3_BUCKET_KEY_NAME }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve
